server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/v1/contactUs
            - Path=/api/v1/faqs
          filters:
            - StripPrefix=0

        - id: support-service
          uri: lb://support-service
          predicates:
            - Path=/api/v1/complaints
            - Path=/api/v1/suggestions
          filters:
            - StripPrefix=0

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/cards
            - Path=/api/v1/payments
          filters:
            - StripPrefix=0

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/categories
            - Path=/api/v1/products
          filters:
            - StripPrefix=0

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/v1/addresses
            - Path=/api/v1/favorites
            - Path=/api/v1/profiles
            - Path=/api/v1/reviews
            - Path=/api/v1/preferences
          filters:
            - StripPrefix=0

        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/api/v1/baskets
            - Path=/api/v1/orders
          filters:
            - StripPrefix=0

        - id: media-service
          uri: http://media-service:8085
          predicates:
            - Path=/api/v1/media/**
          filters:
            - StripPrefix=0


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-discovery:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      probes:
        enabled: true

