global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'service-discovery'
    static_configs:
      - targets: ['service-discovery:8761']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'support-service'
    static_configs:
      - targets: ['support-service:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8084']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'profile-service'
    static_configs:
      - targets: ['profile-service:8085']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'shopping-service'
    static_configs:
      - targets: ['shopping-service:8086']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8087']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'media-service'
    static_configs:
      - targets: ['media-service:8085']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'postgres-identity'
    static_configs:
      - targets: ['postgres-exporter-identity:9187']

  - job_name: 'postgres-content'
    static_configs:
      - targets: ['postgres-exporter-content:9187']

  - job_name: 'postgres-support'
    static_configs:
      - targets: ['postgres-exporter-support:9187']

  - job_name: 'postgres-product'
    static_configs:
      - targets: ['postgres-exporter-product:9187']

  - job_name: 'postgres-profile'
    static_configs:
      - targets: ['postgres-exporter-profile:9187']

  - job_name: 'postgres-shopping'
    static_configs:
      - targets: ['postgres-exporter-shopping:9187']

  - job_name: 'postgres-payment'
    static_configs:
      - targets: ['postgres-exporter-payment:9187']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14268']
    metrics_path: '/metrics'
